service:
  name: bible-translator

custom:
  region: ${opt:region, 'us-east-1'}
  stage: "${opt:stage, self:provider.stage}"
  prod:
    GATEWAY_URL: '/${self:custom.stage}/'
  dev:
    GATEWAY_URL: "http://localhost:3000/"

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs8.10
  environment:
    TRANSLATE_API_URL: "${self:custom.${self:custom.stage}.GATEWAY_URL}api/translate"

plugins:
  - serverless-dynamic-dotenv
  - serverless-offline
  - serverless-webpack

functions:
  index:
    handler: src/handlers/index.index
    events:
      - http:
          method: get
          path: /
  todaysReading:
    handler: src/handlers/todays-reading.todaysReading
    events:
      - http:
          method: get
          path: todays-reading
  translateApi:
    handler: src/handlers/translate-api.translate
    events:
      - http:
          method: get
          path: api/translate
          cors: true
